import smtplib
import os
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
from supabase import create_client, Client
import datetime

load_dotenv()
supabase: Client = create_client(os.environ.get("SUPABASE_URL"), os.environ.get("SUPABASE_KEY"))
EMAIL_USER = os.environ.get("EMAIL_USER")
EMAIL_PASS = os.environ.get("EMAIL_PASS")

def send_email():
    print("📧 Sending via Email...")
    
    response = supabase.table("digests").select("email_html").order("id", desc=True).limit(1).execute()
    
    if not response.data:
        print("Empty DB.")
        return

    # Берем чистый HTML от AI
    ai_html_content = response.data[0]['email_html']
    today_date = datetime.date.today().strftime("%d %B %Y")
    
    # Шаблон письма (wrapper)
    full_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background: #f4f4f4; padding: 20px; }}
            .box {{ max-width: 600px; margin: 0 auto; background: #fff; padding: 40px; border-radius: 8px; }}
            h3 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 10px; margin-top: 30px; }}
            ul {{ padding-left: 20px; }}
            li {{ margin-bottom: 10px; }}
            a {{ color: #3498db; text-decoration: none; }}
            .footer {{ margin-top: 30px; font-size: 12px; color: #999; text-align: center; }}
        </style>
    </head>
    <body>
        <div class="box">
            <h1 style="text-align: center;">☕ Sunday Digest</h1>
            <p style="text-align: center; color: #777;">{today_date}</p>
            <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
            
            {ai_html_content}
            
            <div class="footer">Generated by Sunday AI</div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"☕ Sunday Digest ({today_date})"
    msg["From"] = f"Sunday Bot <{EMAIL_USER}>"
    msg["To"] = EMAIL_USER
    msg.attach(MIMEText(full_html, "html"))

    try:
        server = smtplib.SMTP_SSL("smtp.gmail.com", 465)
        server.login(EMAIL_USER, EMAIL_PASS)
        server.sendmail(EMAIL_USER, EMAIL_USER, msg.as_string())
        server.quit()
        print("✅ Email Sent!")
    except Exception as e:
        print(f"❌ Error: {e}")

if __name__ == "__main__":
    send_email()